name:                hs-nutshell-algorithms
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/hiratara/hs-nutshell-algorithms#readme
license:             BSD3
author:              Masahiro Honma
maintainer:          hiratara@cpan.org
copyright:           hiratara
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - deepseq
    - mwc-random

executables:
  run-convexhull:
    source-dirs:      app
    main:             run-convexhull.hs
    dependencies:
      - hs-nutshell-algorithms
      - containers
      - data-default-class
      - Chart
      - Chart-diagrams
  bench-convexhulls:
    source-dirs:      app
    main:             bench-convexhulls.hs
    dependencies:
      - hs-nutshell-algorithms
      - containers
      - criterion
